name: buildAndDeploy
on:
  push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: buildAndDeploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        VUE_APP_APIURL: ${{ secrets.VUE_APP_APIURL }}
        VUE_APP_MANAGER: ${{ secrets.VUE_APP_MANAGER }}
        VUE_APP_SITEKEY: ${{ secrets.VUE_APP_SITEKEY }}
        BRANCH: gh-pages
        FOLDER: dist
        BUILD_SCRIPT: npm install && npm run build
